Add polish

diff --git a/upm b/upm
--- a/upm
+++ b/upm
@@ -32,23 +32,60 @@ else
     if [[ $1 = "--help" || $1 = "-h" ]]; then
         usage
     elif [[ $1 = "-i" || $1 = "--install" ]]; then
+        if [[ $# -gt 2 || $# -lt 2 ]]; then
+            echo "Needs 2 arguments"
+            usage
+            exit 1
+        fi
         apt-update
         apt install $2 -y
     elif [[ $1 = "-ppa" || $1 = "--add-ppa" ]]; then
+        if [[ $# -gt 3 || $# -lt 3 ]]; then
+            echo "Needs 3 arguments"
+            usage
+            exit 1
+        fi
         add-apt-repository ppa:$2/$3
         apt update
     elif [[ $1 = "--ppa-install" ]]; then
+        if [[ $# -gt 4 || $# -lt 4 ]]; then
+            echo "Needs 4 arguments"
+            usage
+            exit 1
+        fi
         add-apt-repository ppa:$2/$3
         apt update
         apt install $4
     elif [[ $1 = "-r" || $1 = "--remove" ]]; then
+        if [[ $# -gt 2 || $# -lt 2 ]]; then
+            echo "Needs 2 arguments"
+            usage
+            exit 1
+        fi
         apt remove $2
         apt update
     elif [[ $1 = "-rppa" || $1 = "--remove-ppa" ]]; then
+        if [[ $# -gt 3 || $# -lt 3 ]]; then
+            echo "Needs 3 arguments"
+            usage
+            exit 1
+        fi
         add-apt-repository --remove ppa:$2/$3
     elif [[ $1 = "-pdr" || $1 = "--ppa-direct-remove" ]]; then
+        if [[ $# -gt 4 || $# -lt 4 ]]; then
+            echo "Needs 4 arguments"
+            usage
+            exit 1
+        fi
         apt remove $4
         add-apt-repository --remove ppa:$2/$3
         apt update
+    else
+        if [[ -z $1 ]]; then
+            usage
+        else
+            echo "Invalid Argument:"
+            usage
+        fi
     fi
 fi
